// build.sbt for example 'hello'
// by George K. Thiruvathukal
//
// Generated by script/build.py
//
// This and the script may change at any time in the future,
// so please do not depend on the contents you see here.

name := "gcd"

scalaSource in Compile := baseDirectory.value

scalaSource in Test := baseDirectory.value

scalaVersion := "2.11.5"

resolvers += "loyolachicagocode@bintray" at "http://dl.bintray.com/loyolachicagocode/maven"

libraryDependencies += "edu.luc.cs" %% "introcs-scala-ui" % "0.1.11"
libraryDependencies += "com.novocode" % "junit-interface" % "0.11"
libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.1"

