TEMPLATE="""// build.sbt for example '%(name)s'
// by George K. Thiruvathukal
//
// Generated by script/build.py
//
// This and the script may change at any time in the future,
// so please do not depend on the contents you see here.

name := "%(name)s"

// This allows us to keep the source code and tests in the base directory instead
// of the usual src/{main,test}/scala folder structure. Makes it easier for CS1
// students!

scalaSource in Compile := baseDirectory.value
scalaSource in Test := baseDirectory.value

scalaVersion := "%(scala)s"

// UI library provided by George K. Thiruvathukal and Andy Harrington (based on C# book)
// Thanks to Konstantin for the Bintray integration!

resolvers += "loyolachicagocode@bintray" at "http://dl.bintray.com/loyolachicagocode/maven"
libraryDependencies += "edu.luc.cs" %(pct)s%(pct)s "introcs-scala-ui" %(pct)s "0.1.11"

// JUnit Support
libraryDependencies += "com.novocode" %(pct)s "junit-interface" %(pct)s "0.11"

// ScalaTest Support
libraryDependencies += "org.scalatest" %(pct)s%(pct)s "scalatest" %(pct)s "2.2.1"

"""
