TEMPLATE="""// build.sbt for example '%(name)s'
// by George K. Thiruvathukal
//
// Generated by script/build.py
//
// This and the script may change at any time in the future,
// so please do not depend on the contents you see here.

name := "%(name)s"

scalaVersion := "%(scala)s"

resolvers += "loyolachicagocode@bintray" at "http://dl.bintray.com/loyolachicagocode/maven"

libraryDependencies += "edu.luc.cs" %(pct)s%(pct)s "introcs-scala-ui" %(pct)s "0.1.11"
"""
